from backend.common.constants import *

# Vector DB Embedding Models
VECTOR_DB_EMBEDDING_MODELS = [
    BAAI_BGE_M3,
    LABSE,
    SNOWFLAKE_SNOWFLAKE_ARCTIC_EMBED_L_V2_0,
    EMRECAN_BERT_BASE_TURKISH_CASED_MEAN_NLI_STSB_TR,
    SENTENCE_TRANSFORMERS_ALL_MPNET_BASE_V2
]

LLM_MODELS = [
  DEEPSEEK_R1_DISTILL_LLAMA_70B,
  LLAMA_3_2_90B_VISION_PREVIEW,
  LLAMA_3_3_70B_VERSATILE,
  META_LLAMA_LLAMA_4_MAVERICK_17B_128E_INSTRUCT,
  MISTRAL_SABA_24B
]

RAG_OPTIONS = {
  CROSS_ENCODER_OPTION: [
    CROSS_ENCODER_MS_MARCO_MINILM_L6_V2,
    MIXEDBREAD_AI_MXBAI_RERANK_BASE_V1,
    BAAI_BGE_RERANKER_V2_M3,
    ALIBABA_NLP_GTE_MULTILINGUAL_RERANKER_BASE
  ],
  "NEW": ["ASDASD"]
}

CONFIG = {
  "EMBEDDING_MODELS": VECTOR_DB_EMBEDDING_MODELS,
  "LLM_MODELS": LLM_MODELS,
  "RAG_OPTIONS": RAG_OPTIONS
}


# Global Vector DB Configuration
GLOBAL_VECTOR_DB_INITIAL_EMBEDDING_MODEL = LABSE
GLOBAL_VECTOR_DB_INITIAL_CHUNK_SIZE = 500
GLOBAL_VECTOR_DB_INITIAL_CHUNK_OVERLAP = 50

# Cross Encoder Configuration
CROSS_ENCODER_K = 7
SKG_AGENT_SIMILAR_VECTOR_K = 10



